### Importando a base de dados

In [1]:
import pandas as pd
import json
import codecs

In [2]:
with codecs.open('dataset/records.json', 'r', 'utf-8-sig') as f:
    data = f.read()

In [3]:
data = data.replace("ï»¿", "")

In [4]:
json_data = json.loads(data)

In [5]:
df = pd.json_normalize(json_data)

In [6]:
df.columns

Index(['n.identity', 'n.labels', 'n.properties.instructions',
       'n.properties.updated_at', 'n.properties.name', 'n.properties.active',
       'n.properties.created_at', 'n.properties.description',
       'n.properties.ingredients', 'n.elementId', 'r.identity', 'r.start',
       'r.end', 'r.type', 'r.elementId', 'r.startNodeElementId',
       'r.endNodeElementId', 'n.properties.identifier',
       'n.properties.password', 'n.properties.administrator',
       'n.properties.bio', 'n.properties.birthDate', 'n.properties.email',
       'n.properties.label'],
      dtype='object')

In [7]:
df.shape

(6000, 24)

In [8]:
df.head()

,n.identity,n.labels,n.properties.instructions,n.properties.updated_at,n.properties.name,n.properties.active,n.properties.created_at,n.properties.description,n.properties.ingredients,n.elementId,...,r.elementId,r.startNodeElementId,r.endNodeElementId,n.properties.identifier,n.properties.password,n.properties.administrator,n.properties.bio,n.properties.birthDate,n.properties.email,n.properties.label
0,106,[recipe],Molestiae dolores quod voluptate aut rerum mai...,2024-04-29T17:56:20.528906400,Mushroom Risotto,True,2024-04-29T17:56:20.528906400,Aperiam saepe odio fugit delectus occaecati et.,1/2 Xícara Atum,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:0,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5,[user],NaN,2024-04-29T17:56:19.858514600,Luana Arriaga,True,2024-04-29T17:56:19.858514600,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:0,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,@luizfelipe.taveira,123456,False,Quia tenetur dolor quo maxime ut hic.,2024-04-29,lais.castanho@bol.com.br,NaN
2,106,[recipe],Molestiae dolores quod voluptate aut rerum mai...,2024-04-29T17:56:20.528906400,Mushroom Risotto,True,2024-04-29T17:56:20.528906400,Aperiam saepe odio fugit delectus occaecati et.,1/2 Xícara Atum,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:87,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,87,[tag],NaN,2024-04-29T17:56:20.427379900,NaN,True,2024-04-29T17:56:20.427379900,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:87,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:87,NaN,NaN,NaN,NaN,NaN,NaN,TAG 81
4,106,[recipe],Molestiae dolores quod voluptate aut rerum mai...,2024-04-29T17:56:20.528906400,Mushroom Risotto,True,2024-04-29T17:56:20.528906400,Aperiam saepe odio fugit delectus occaecati et.,1/2 Xícara Atum,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6000 entries, 0 to 5999
Data columns (total 24 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   n.identity                  6000 non-null   int64
 1   n.labels                    6000 non-null   object
 2   n.properties.instructions   3000 non-null   object
 3   n.properties.updated_at     6000 non-null   object
 4   n.properties.name           4000 non-null   object
 5   n.properties.active         6000 non-null   bool
 6   n.properties.created_at     6000 non-null   object
 7   n.properties.description    3000 non-null   object
 8   n.properties.ingredients    3000 non-null   object
 9   n.elementId                 6000 non-null   object
 10  r.identity                  6000 non-null   int64
 11  r.start                     6000 non-null   int64
 12  r.end                       6000 non-null   int64
 13  r.type                      6000 non-null   object
 14  r.elementId                 6000 non-null   object
 15  r.startNodeElementId        6000 non-null   object
 16  r.endNodeElementId          6000 non-null   object
 17  n.properties.identifier     1000 non-null   object
 18  n.properties.password       1000 non-null   object
 19  n.properties.administrator  1000 non-null   object
 20  n.properties.bio            1000 non-null   object
 21  n.properties.birthDate      1000 non-null   object
 22  n.properties.email          1000 non-null   object
 23  n.properties.label          2000 non-null   object
dtypes: bool(1), int64(4), object(19)
memory usage: 1.1+ MB

### Separando o que é Receita, Usuário e Tag

#### Tratando as labels...

In [10]:
df["n.labels"] = df["n.labels"].astype("string")

In [11]:
df['n.labels'].value_counts()

n.labels
['recipe']    3000
['tag']       2000
['user']      1000
Name: count, dtype: Int64

#### Dataframe de Receitas

In [12]:
df_recipes = df[df["n.labels"] == "['recipe']"]
df_recipes

,n.identity,n.labels,n.properties.instructions,n.properties.updated_at,n.properties.name,n.properties.active,n.properties.created_at,n.properties.description,n.properties.ingredients,n.elementId,...,r.elementId,r.startNodeElementId,r.endNodeElementId,n.properties.identifier,n.properties.password,n.properties.administrator,n.properties.bio,n.properties.birthDate,n.properties.email,n.properties.label
0,106,['recipe'],Molestiae dolores quod voluptate aut rerum mai...,2024-04-29T17:56:20.528906400,Mushroom Risotto,True,2024-04-29T17:56:20.528906400,Aperiam saepe odio fugit delectus occaecati et.,1/2 Xícara Atum,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:0,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,106,['recipe'],Molestiae dolores quod voluptate aut rerum mai...,2024-04-29T17:56:20.528906400,Mushroom Risotto,True,2024-04-29T17:56:20.528906400,Aperiam saepe odio fugit delectus occaecati et.,1/2 Xícara Atum,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:87,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,106,['recipe'],Molestiae dolores quod voluptate aut rerum mai...,2024-04-29T17:56:20.528906400,Mushroom Risotto,True,2024-04-29T17:56:20.528906400,Aperiam saepe odio fugit delectus occaecati et.,1/2 Xícara Atum,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:32,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,107,['recipe'],Debitis dolore vitae. Provident consequatur no...,2024-04-29T17:56:20.711850700,Chicken Parm,True,2024-04-29T17:56:20.711850700,Est vel ut aut vel repellat qui.,1/4 Litro Pêra,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:107,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:3,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:107,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,107,['recipe'],Debitis dolore vitae. Provident consequatur no...,2024-04-29T17:56:20.711850700,Chicken Parm,True,2024-04-29T17:56:20.711850700,Est vel ut aut vel repellat qui.,1/4 Litro Pêra,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:107,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:4,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:107,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5990,1104,['recipe'],Nostrum vero recusandae distinctio suscipit ea...,2024-04-29T17:58:23.120425400,Tacos,True,2024-04-29T17:58:23.120425400,Ut ipsam eum totam maiores excepturi suscipit ...,3 Copo Americano Água De Côco,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1104,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2995,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1104,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:16,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5992,1104,['recipe'],Nostrum vero recusandae distinctio suscipit ea...,2024-04-29T17:58:23.120425400,Tacos,True,2024-04-29T17:58:23.120425400,Ut ipsam eum totam maiores excepturi suscipit ...,3 Copo Americano Água De Côco,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1104,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2996,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1104,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:58,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5994,1105,['recipe'],Atque dolor explicabo recusandae. Tempora volu...,2024-04-29T17:58:23.418908600,California Maki,True,2024-04-29T17:58:23.418908600,Et fuga explicabo ex voluptatibus error.,1/3 Colher de Chá Nozes,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1105,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2997,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1105,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5996,1105,['recipe'],Atque dolor explicabo recusandae. Tempora volu...,2024-04-29T17:58:23.418908600,California Maki,True,2024-04-29T17:58:23.418908600,Et fuga explicabo ex voluptatibus error.,1/3 Colher de Chá Nozes,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1105,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2998,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1105,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5998,1105,['recipe'],Atque dolor explicabo recusandae. Tempora volu...,2024-04-29T17:58:23.418908600,California Maki,True,2024-04-29T17:58:23.418908600,Et fuga explicabo ex voluptatibus error.,1/3 Colher de Chá Nozes,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1105,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2999,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1105,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:97,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### Dataframe de Usuários

In [13]:
df_users = df[df["n.labels"] == "['user']"]
df_users

,n.identity,n.labels,n.properties.instructions,n.properties.updated_at,n.properties.name,n.properties.active,n.properties.created_at,n.properties.description,n.properties.ingredients,n.elementId,...,r.elementId,r.startNodeElementId,r.endNodeElementId,n.properties.identifier,n.properties.password,n.properties.administrator,n.properties.bio,n.properties.birthDate,n.properties.email,n.properties.label
1,5,['user'],NaN,2024-04-29T17:56:19.858514600,Luana Arriaga,True,2024-04-29T17:56:19.858514600,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:0,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,@luizfelipe.taveira,123456,False,Quia tenetur dolor quo maxime ut hic.,2024-04-29,lais.castanho@bol.com.br,NaN
7,5,['user'],NaN,2024-04-29T17:56:19.858514600,Luana Arriaga,True,2024-04-29T17:56:19.858514600,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:3,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:107,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,@luizfelipe.taveira,123456,False,Quia tenetur dolor quo maxime ut hic.,2024-04-29,lais.castanho@bol.com.br,NaN
13,5,['user'],NaN,2024-04-29T17:56:19.858514600,Luana Arriaga,True,2024-04-29T17:56:19.858514600,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:6,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:108,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,@luizfelipe.taveira,123456,False,Quia tenetur dolor quo maxime ut hic.,2024-04-29,lais.castanho@bol.com.br,NaN
19,5,['user'],NaN,2024-04-29T17:56:19.858514600,Luana Arriaga,True,2024-04-29T17:56:19.858514600,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:9,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:109,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,@luizfelipe.taveira,123456,False,Quia tenetur dolor quo maxime ut hic.,2024-04-29,lais.castanho@bol.com.br,NaN
25,5,['user'],NaN,2024-04-29T17:56:19.858514600,Luana Arriaga,True,2024-04-29T17:56:19.858514600,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:12,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:110,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,@luizfelipe.taveira,123456,False,Quia tenetur dolor quo maxime ut hic.,2024-04-29,lais.castanho@bol.com.br,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5971,5,['user'],NaN,2024-04-29T17:56:19.858514600,Luana Arriaga,True,2024-04-29T17:56:19.858514600,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2985,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1101,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,@luizfelipe.taveira,123456,False,Quia tenetur dolor quo maxime ut hic.,2024-04-29,lais.castanho@bol.com.br,NaN
5977,5,['user'],NaN,2024-04-29T17:56:19.858514600,Luana Arriaga,True,2024-04-29T17:56:19.858514600,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2988,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1102,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,@luizfelipe.taveira,123456,False,Quia tenetur dolor quo maxime ut hic.,2024-04-29,lais.castanho@bol.com.br,NaN
5983,5,['user'],NaN,2024-04-29T17:56:19.858514600,Luana Arriaga,True,2024-04-29T17:56:19.858514600,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2991,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1103,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,@luizfelipe.taveira,123456,False,Quia tenetur dolor quo maxime ut hic.,2024-04-29,lais.castanho@bol.com.br,NaN
5989,5,['user'],NaN,2024-04-29T17:56:19.858514600,Luana Arriaga,True,2024-04-29T17:56:19.858514600,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2994,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1104,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,@luizfelipe.taveira,123456,False,Quia tenetur dolor quo maxime ut hic.,2024-04-29,lais.castanho@bol.com.br,NaN
5995,5,['user'],NaN,2024-04-29T17:56:19.858514600,Luana Arriaga,True,2024-04-29T17:56:19.858514600,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2997,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1105,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,@luizfelipe.taveira,123456,False,Quia tenetur dolor quo maxime ut hic.,2024-04-29,lais.castanho@bol.com.br,NaN

#### Dataframe de Tags

In [14]:
df_tags = df[df["n.labels"] == "['tag']"]
df_tags

,n.identity,n.labels,n.properties.instructions,n.properties.updated_at,n.properties.name,n.properties.active,n.properties.created_at,n.properties.description,n.properties.ingredients,n.elementId,...,r.elementId,r.startNodeElementId,r.endNodeElementId,n.properties.identifier,n.properties.password,n.properties.administrator,n.properties.bio,n.properties.birthDate,n.properties.email,n.properties.label
3,87,['tag'],NaN,2024-04-29T17:56:20.427379900,NaN,True,2024-04-29T17:56:20.427379900,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:87,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:87,NaN,NaN,NaN,NaN,NaN,NaN,TAG 81
5,32,['tag'],NaN,2024-04-29T17:56:20.178891900,NaN,True,2024-04-29T17:56:20.178891900,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:32,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:32,NaN,NaN,NaN,NaN,NaN,NaN,TAG 26
9,27,['tag'],NaN,2024-04-29T17:56:20.155899700,NaN,True,2024-04-29T17:56:20.155899700,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:27,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:4,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:107,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:27,NaN,NaN,NaN,NaN,NaN,NaN,TAG 21
11,83,['tag'],NaN,2024-04-29T17:56:20.409618100,NaN,True,2024-04-29T17:56:20.409618100,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:83,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:107,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:83,NaN,NaN,NaN,NaN,NaN,NaN,TAG 77
15,80,['tag'],NaN,2024-04-29T17:56:20.394577300,NaN,True,2024-04-29T17:56:20.394577300,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:80,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:7,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:108,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:80,NaN,NaN,NaN,NaN,NaN,NaN,TAG 74
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5987,59,['tag'],NaN,2024-04-29T17:56:20.301914500,NaN,True,2024-04-29T17:56:20.301914500,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:59,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2993,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1103,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:59,NaN,NaN,NaN,NaN,NaN,NaN,TAG 53
5991,16,['tag'],NaN,2024-04-29T17:56:20.090529600,NaN,True,2024-04-29T17:56:20.090529600,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:16,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2995,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1104,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:16,NaN,NaN,NaN,NaN,NaN,NaN,TAG 10
5993,58,['tag'],NaN,2024-04-29T17:56:20.297402700,NaN,True,2024-04-29T17:56:20.297402700,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:58,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2996,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1104,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:58,NaN,NaN,NaN,NaN,NaN,NaN,TAG 52
5997,10,['tag'],NaN,2024-04-29T17:56:20.054221600,NaN,True,2024-04-29T17:56:20.054221600,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:10,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2998,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1105,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:10,NaN,NaN,NaN,NaN,NaN,NaN,TAG 4
5999,97,['tag'],NaN,2024-04-29T17:56:20.470660800,NaN,True,2024-04-29T17:56:20.470660800,NaN,NaN,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:97,...,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2999,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1105,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:97,NaN,NaN,NaN,NaN,NaN,NaN,TAG 91

In [15]:
df_tags['n.properties.label'].unique()

array(['TAG 81', 'TAG 26', 'TAG 21', 'TAG 77', 'TAG 74', 'TAG 47',
       'TAG 99', 'TAG 62', 'TAG 97', 'TAG 34', 'TAG 48', 'TAG 52',
       'TAG 64', 'TAG 65', 'TAG 87', 'TAG 76', 'TAG 5', 'TAG 33', 'TAG 0',
       'TAG 89', 'TAG 82', 'TAG 84', 'TAG 79', 'TAG 96', 'TAG 6',
       'TAG 91', 'TAG 58', 'TAG 83', 'TAG 8', 'TAG 20', 'TAG 71',
       'TAG 32', 'TAG 70', 'TAG 11', 'TAG 54', 'TAG 43', 'TAG 78',
       'TAG 41', 'TAG 57', 'TAG 93', 'TAG 2', 'TAG 75', 'TAG 90', 'TAG 3',
       'TAG 31', 'TAG 50', 'TAG 68', 'TAG 69', 'TAG 88', 'TAG 95',
       'TAG 23', 'TAG 66', 'TAG 30', 'TAG 49', 'TAG 53', 'TAG 37',
       'TAG 14', 'TAG 40', 'TAG 22', 'TAG 86', 'TAG 63', 'TAG 24',
       'TAG 92', 'TAG 10', 'TAG 18', 'TAG 46', 'TAG 61', 'TAG 51',
       'TAG 9', 'TAG 13', 'TAG 72', 'TAG 60', 'TAG 94', 'TAG 19',
       'TAG 56', 'TAG 27', 'TAG 98', 'TAG 55', 'TAG 38', 'TAG 15',
       'TAG 45', 'TAG 73', 'TAG 4', 'TAG 16', 'TAG 28', 'TAG 1', 'TAG 44',
       'TAG 39', 'TAG 42', 'TAG 7', 'TAG 85', 'TAG 35', 'TAG 36',
       'TAG 17', 'TAG 59', 'TAG 25', 'TAG 29', 'TAG 12', 'TAG 67',
       'TAG 80'], dtype=object)

#### Resultado:

Somente será trabalhado receitas e tags, pois os usuários são apenas os que criaram... e somente um criou até agr...

### Data Cleaning

#### Recipes

##### Duplicated values

In [16]:
df_recipes.shape

(3000, 24)

In [17]:
df_recipes['n.identity'].duplicated().sum()

2000

In [18]:
df_recipes = df_recipes.drop_duplicates(subset="n.identity")

In [19]:
df_recipes.shape

(1000, 24)

##### Join tags

In [20]:
df_tags[['n.identity','r.elementId', 'r.startNodeElementId']].head(10)

,n.identity,r.elementId,r.startNodeElementId
3,87,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106
5,32,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:2,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106
9,27,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:4,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:107
11,83,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:107
15,80,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:7,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:108
17,53,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:8,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:108
21,105,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:10,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:109
23,68,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:11,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:109
27,103,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:13,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:110
29,40,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:14,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:110

In [21]:
df_recipes[['n.identity', 'r.elementId', 'r.startNodeElementId']].head(10)

,n.identity,r.elementId,r.startNodeElementId
0,106,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:0,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106
6,107,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:3,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:107
12,108,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:6,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:108
18,109,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:9,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:109
24,110,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:12,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:110
30,111,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:15,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:111
36,112,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:18,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:112
42,113,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:21,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:113
48,114,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:24,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:114
54,115,5:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:27,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:115

In [22]:
for index, row in df_recipes.iterrows():
    identity = row['n.identity']
    tags = df_tags.loc[df_tags['r.startNodeElementId'] == f'4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:{identity}']
    tags_list = tags['n.properties.label'].values.tolist()
    df_recipes.at[index, 'tags'] = ', '.join(tags_list)

C:\Users\rafae\AppData\Local\Temp\ipykernel_23028\3648614920.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_recipes.at[index, 'tags'] = ', '.join(tags_list)

In [23]:
df_recipes

,n.identity,n.labels,n.properties.instructions,n.properties.updated_at,n.properties.name,n.properties.active,n.properties.created_at,n.properties.description,n.properties.ingredients,n.elementId,...,r.startNodeElementId,r.endNodeElementId,n.properties.identifier,n.properties.password,n.properties.administrator,n.properties.bio,n.properties.birthDate,n.properties.email,n.properties.label,tags
0,106,['recipe'],Molestiae dolores quod voluptate aut rerum mai...,2024-04-29T17:56:20.528906400,Mushroom Risotto,True,2024-04-29T17:56:20.528906400,Aperiam saepe odio fugit delectus occaecati et.,1/2 Xícara Atum,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,...,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:106,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"TAG 81, TAG 26"
6,107,['recipe'],Debitis dolore vitae. Provident consequatur no...,2024-04-29T17:56:20.711850700,Chicken Parm,True,2024-04-29T17:56:20.711850700,Est vel ut aut vel repellat qui.,1/4 Litro Pêra,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:107,...,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:107,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"TAG 21, TAG 77"
12,108,['recipe'],Nihil omnis consequuntur qui eveniet. Culpa qu...,2024-04-29T17:56:20.739398700,Arepas,True,2024-04-29T17:56:20.739398700,Ea rerum quis quod est ratione sit qui.,3 Copo Americano Linguiça,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:108,...,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:108,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"TAG 74, TAG 47"
18,109,['recipe'],Et dolor cum. Consequatur soluta vero dolor is...,2024-04-29T17:56:20.761887900,Pho,True,2024-04-29T17:56:20.761887900,Maxime inventore quis consequatur maxime velit...,Pitada Colher de Chá Mandarins,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:109,...,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:109,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"TAG 99, TAG 62"
24,110,['recipe'],Perferendis illo eveniet ab voluptas et et atq...,2024-04-29T17:56:20.792022400,Caprese Salad,True,2024-04-29T17:56:20.792022400,Ut illum repellendus unde sapiente fugit est r...,1/3 Litro Couve,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:110,...,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:110,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"TAG 97, TAG 34"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5970,1101,['recipe'],Tenetur nihil sunt dignissimos ex quia. Exerci...,2024-04-29T17:58:22.198555700,Tiramisù,True,2024-04-29T17:58:22.198555700,Vitae aut qui doloremque ut maiores error ea.,1/3 Litro Star Anise,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1101,...,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1101,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"TAG 4, TAG 1"
5976,1102,['recipe'],Mollitia delectus eligendi adipisci atque ea. ...,2024-04-29T17:58:22.517022000,Stinky Tofu,True,2024-04-29T17:58:22.516022200,Vitae quo optio.,1 Colher de Sopa Edamame,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1102,...,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1102,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"TAG 91, TAG 69"
5982,1103,['recipe'],Et cum aliquam illum aliquid. Eos perspiciatis...,2024-04-29T17:58:22.824835900,Caprese Salad,True,2024-04-29T17:58:22.824835900,Accusamus ducimus itaque perferendis culpa ull...,1/2 Copo Americano Salsisha,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1103,...,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1103,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"TAG 37, TAG 53"
5988,1104,['recipe'],Nostrum vero recusandae distinctio suscipit ea...,2024-04-29T17:58:23.120425400,Tacos,True,2024-04-29T17:58:23.120425400,Ut ipsam eum totam maiores excepturi suscipit ...,3 Copo Americano Água De Côco,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1104,...,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1104,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"TAG 10, TAG 52"
5994,1105,['recipe'],Atque dolor explicabo recusandae. Tempora volu...,2024-04-29T17:58:23.418908600,California Maki,True,2024-04-29T17:58:23.418908600,Et fuga explicabo ex voluptatibus error.,1/3 Colher de Chá Nozes,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1105,...,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:1105,4:7c319bbf-fffb-4ba6-8cfe-e34a5331cbe2:5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"TAG 4, TAG 91"

##### Drop columns

In [24]:
columns = ['n.identity', 'n.properties.name' , 'n.properties.instructions', 'n.properties.ingredients', 'n.properties.description', 'tags']
columns_renamed = ['id', 'name', 'instructions', 'ingredients', 'description', 'tags']

In [25]:
df_recipes = df_recipes[columns]
df_recipes.columns = columns_renamed

In [26]:
df_recipes

,id,name,instructions,ingredients,description,tags
0,106,Mushroom Risotto,Molestiae dolores quod voluptate aut rerum mai...,1/2 Xícara Atum,Aperiam saepe odio fugit delectus occaecati et.,"TAG 81, TAG 26"
6,107,Chicken Parm,Debitis dolore vitae. Provident consequatur no...,1/4 Litro Pêra,Est vel ut aut vel repellat qui.,"TAG 21, TAG 77"
12,108,Arepas,Nihil omnis consequuntur qui eveniet. Culpa qu...,3 Copo Americano Linguiça,Ea rerum quis quod est ratione sit qui.,"TAG 74, TAG 47"
18,109,Pho,Et dolor cum. Consequatur soluta vero dolor is...,Pitada Colher de Chá Mandarins,Maxime inventore quis consequatur maxime velit...,"TAG 99, TAG 62"
24,110,Caprese Salad,Perferendis illo eveniet ab voluptas et et atq...,1/3 Litro Couve,Ut illum repellendus unde sapiente fugit est r...,"TAG 97, TAG 34"
...,...,...,...,...,...,...
5970,1101,Tiramisù,Tenetur nihil sunt dignissimos ex quia. Exerci...,1/3 Litro Star Anise,Vitae aut qui doloremque ut maiores error ea.,"TAG 4, TAG 1"
5976,1102,Stinky Tofu,Mollitia delectus eligendi adipisci atque ea. ...,1 Colher de Sopa Edamame,Vitae quo optio.,"TAG 91, TAG 69"
5982,1103,Caprese Salad,Et cum aliquam illum aliquid. Eos perspiciatis...,1/2 Copo Americano Salsisha,Accusamus ducimus itaque perferendis culpa ull...,"TAG 37, TAG 53"
5988,1104,Tacos,Nostrum vero recusandae distinctio suscipit ea...,3 Copo Americano Água De Côco,Ut ipsam eum totam maiores excepturi suscipit ...,"TAG 10, TAG 52"
5994,1105,California Maki,Atque dolor explicabo recusandae. Tempora volu...,1/3 Colher de Chá Nozes,Et fuga explicabo ex voluptatibus error.,"TAG 4, TAG 91"

### Data Augmentation

### Ingredients

#### Getting all unique values of Ingredients

In [27]:
df_recipes.head(1)

,id,name,instructions,ingredients,description,tags
0,106,Mushroom Risotto,Molestiae dolores quod voluptate aut rerum mai...,1/2 Xícara Atum,Aperiam saepe odio fugit delectus occaecati et.,"TAG 81, TAG 26"

In [28]:
display(f'Unique ingredients: {len(df_recipes['ingredients'].unique())}')

'Unique ingredients: 953'

In [29]:
df_ingredients = df_recipes['ingredients'].str.split(',', expand=True).stack().reset_index(level=1, drop=True).to_frame('ingredients')

In [30]:
df_ingredients.head()

                       ingredients
0                  1/2 Xícara Atum
6                   1/4 Litro Pêra
12       3 Copo Americano Linguiça
18  Pitada Colher de Chá Mandarins
24                 1/3 Litro Couve

#### Remove Numbers

In [31]:
import re
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

In [32]:
df_ingredients['ingredients'] = df_ingredients['ingredients'].apply(remove_numbers)

In [33]:
df_ingredients['ingredients']

0                        / Xícara Atum
6                         / Litro Pêra
12             Copo Americano Linguiça
18      Pitada Colher de Chá Mandarins
24                       / Litro Couve
                     ...
5970                / Litro Star Anise
5976            Colher de Sopa Edamame
5982         / Copo Americano Salsisha
5988       Copo Americano Água De Côco
5994             / Colher de Chá Nozes
Name: ingredients, Length: 1000, dtype: object

#### Remove Unit Measurement

In [34]:
units = ['Xícara', 'Litro', 'Copo Americano', 'Pitada', 'Colher de Chá', 'Colher de Sopa']
def remove_units(text, units):
    for unit in units:
        text = text.replace(unit, '')
    return text

In [35]:
df_ingredients['ingredients'] = df_ingredients['ingredients'].apply(lambda x: remove_units(x, units))

In [36]:
df_ingredients['ingredients']

0              /  Atum
6              /  Pêra
12            Linguiça
18           Mandarins
24            /  Couve
             ...
5970     /  Star Anise
5976           Edamame
5982       /  Salsisha
5988      Água De Côco
5994          /  Nozes
Name: ingredients, Length: 1000, dtype: object

#### Remove Special Characters

In [37]:
special_characters = '[!"#$%°&\'()*+,-./:;<=>?@[\\]^_`{|}~]'
def remove_special_characters(df, column_name, characters_to_remove):
    df[column_name] = df[column_name].str.replace(f'[{re.escape(characters_to_remove)}]', ' ', regex=True)
    return df

In [38]:
df_ingredients = remove_special_characters(df_ingredients, 'ingredients', special_characters)

In [39]:
df_ingredients['ingredients'] = df_ingredients['ingredients'].str.strip()

In [40]:
df_ingredients

       ingredients
0             Atum
6             Pêra
12        Linguiça
18       Mandarins
24           Couve
...            ...
5970    Star Anise
5976       Edamame
5982      Salsisha
5988  Água De Côco
5994         Nozes

[1000 rows x 1 columns]

#### Remove Articles, Prepositions

In [41]:
prepositions = ['De ', 'Do ', 'Da ']
def remove_prepositions(text):
    for preposition in prepositions:
        text = text.replace(preposition, '')
    return text

In [42]:
df_ingredients['ingredients'] = df_ingredients['ingredients'].apply(remove_prepositions)

In [43]:
df_ingredients['ingredients']

0             Atum
6             Pêra
12        Linguiça
18       Mandarins
24           Couve
           ...
5970    Star Anise
5976       Edamame
5982      Salsisha
5988     Água Côco
5994         Nozes
Name: ingredients, Length: 1000, dtype: object

#### Adding more ingredients to recipe

In [44]:
import random
ingredients = df_ingredients['ingredients'].unique().tolist()

def get_4_ingredients(x):
    ing = random.choices(ingredients, k=4)
    ing = str(ing).replace('[', '').replace(']', '').replace("'", '').replace(',', '')
    return ing

In [45]:
get_4_ingredients("str")

'Hortelã Óleo Amêndoa Água Côco Stevi'

In [46]:
df_recipes['ingredients'] = df_recipes['ingredients'].apply(get_4_ingredients).astype(str)

C:\Users\rafae\AppData\Local\Temp\ipykernel_23028\2711784302.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_recipes['ingredients'] = df_recipes['ingredients'].apply(get_4_ingredients).astype(str)

In [47]:
df_recipes

,id,name,instructions,ingredients,description,tags
0,106,Mushroom Risotto,Molestiae dolores quod voluptate aut rerum mai...,Pêra Manjerona Anchovas Coentro,Aperiam saepe odio fugit delectus occaecati et.,"TAG 81, TAG 26"
6,107,Chicken Parm,Debitis dolore vitae. Provident consequatur no...,Jewfish Semente Abóbora Vieiras Semente Ajowan,Est vel ut aut vel repellat qui.,"TAG 21, TAG 77"
12,108,Arepas,Nihil omnis consequuntur qui eveniet. Culpa qu...,Manjerona Pão Montanha Salsisha Maçã,Ea rerum quis quod est ratione sit qui.,"TAG 74, TAG 47"
18,109,Pho,Et dolor cum. Consequatur soluta vero dolor is...,Pêra Fermento Em Pó Mandarins Lentilha Vermelha,Maxime inventore quis consequatur maxime velit...,"TAG 99, TAG 62"
24,110,Caprese Salad,Perferendis illo eveniet ab voluptas et et atq...,Bacon Farinha Semente Ajowan Vinagre Vinho Tinto,Ut illum repellendus unde sapiente fugit est r...,"TAG 97, TAG 34"
...,...,...,...,...,...,...
5970,1101,Tiramisù,Tenetur nihil sunt dignissimos ex quia. Exerci...,Soro Leite Farinha Tapioca Canela Alface,Vitae aut qui doloremque ut maiores error ea.,"TAG 4, TAG 1"
5976,1102,Stinky Tofu,Mollitia delectus eligendi adipisci atque ea. ...,Farinha Grão Bico Pêssego Berinjela Farinha Trigo,Vitae quo optio.,"TAG 91, TAG 69"
5982,1103,Caprese Salad,Et cum aliquam illum aliquid. Eos perspiciatis...,Uva Queijo Cabra Damascos Molho Ostras,Accusamus ducimus itaque perferendis culpa ull...,"TAG 37, TAG 53"
5988,1104,Tacos,Nostrum vero recusandae distinctio suscipit ea...,Semente Ajowan Sardinha Beringela Quinoa,Ut ipsam eum totam maiores excepturi suscipit ...,"TAG 10, TAG 52"
5994,1105,California Maki,Atque dolor explicabo recusandae. Tempora volu...,Amendoim Erva Doce Groselha Fubá,Et fuga explicabo ex voluptatibus error.,"TAG 4, TAG 91"

### Tags

#### Getting all unique values of Tags

In [48]:
def create_tags():
    tags = []
    for i in range(100):
        tags.append(f'TAG {i}')
    return tags
tags = create_tags()

#### Adding more tags to recipe

In [49]:
df_recipes['tags'].head()

0     TAG 81, TAG 26
6     TAG 21, TAG 77
12    TAG 74, TAG 47
18    TAG 99, TAG 62
24    TAG 97, TAG 34
Name: tags, dtype: object

In [50]:
df_recipes['tags'] = df_recipes['id'].apply(lambda x: ' '.join(random.choices(tags, k=5)))

C:\Users\rafae\AppData\Local\Temp\ipykernel_23028\374564774.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_recipes['tags'] = df_recipes['id'].apply(lambda x: ' '.join(random.choices(tags, k=5)))

In [51]:
df_recipes['tags'] = df_recipes['tags'].str.replace('G ', 'G')

C:\Users\rafae\AppData\Local\Temp\ipykernel_23028\498415976.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_recipes['tags'] = df_recipes['tags'].str.replace('G ', 'G')

In [52]:
df_recipes

,id,name,instructions,ingredients,description,tags
0,106,Mushroom Risotto,Molestiae dolores quod voluptate aut rerum mai...,Pêra Manjerona Anchovas Coentro,Aperiam saepe odio fugit delectus occaecati et.,TAG43 TAG49 TAG47 TAG7 TAG91
6,107,Chicken Parm,Debitis dolore vitae. Provident consequatur no...,Jewfish Semente Abóbora Vieiras Semente Ajowan,Est vel ut aut vel repellat qui.,TAG3 TAG7 TAG96 TAG58 TAG68
12,108,Arepas,Nihil omnis consequuntur qui eveniet. Culpa qu...,Manjerona Pão Montanha Salsisha Maçã,Ea rerum quis quod est ratione sit qui.,TAG27 TAG42 TAG13 TAG58 TAG83
18,109,Pho,Et dolor cum. Consequatur soluta vero dolor is...,Pêra Fermento Em Pó Mandarins Lentilha Vermelha,Maxime inventore quis consequatur maxime velit...,TAG31 TAG73 TAG1 TAG67 TAG5
24,110,Caprese Salad,Perferendis illo eveniet ab voluptas et et atq...,Bacon Farinha Semente Ajowan Vinagre Vinho Tinto,Ut illum repellendus unde sapiente fugit est r...,TAG94 TAG91 TAG19 TAG4 TAG8
...,...,...,...,...,...,...
5970,1101,Tiramisù,Tenetur nihil sunt dignissimos ex quia. Exerci...,Soro Leite Farinha Tapioca Canela Alface,Vitae aut qui doloremque ut maiores error ea.,TAG57 TAG99 TAG6 TAG74 TAG60
5976,1102,Stinky Tofu,Mollitia delectus eligendi adipisci atque ea. ...,Farinha Grão Bico Pêssego Berinjela Farinha Trigo,Vitae quo optio.,TAG40 TAG68 TAG0 TAG0 TAG42
5982,1103,Caprese Salad,Et cum aliquam illum aliquid. Eos perspiciatis...,Uva Queijo Cabra Damascos Molho Ostras,Accusamus ducimus itaque perferendis culpa ull...,TAG8 TAG25 TAG96 TAG15 TAG47
5988,1104,Tacos,Nostrum vero recusandae distinctio suscipit ea...,Semente Ajowan Sardinha Beringela Quinoa,Ut ipsam eum totam maiores excepturi suscipit ...,TAG44 TAG7 TAG4 TAG26 TAG84
5994,1105,California Maki,Atque dolor explicabo recusandae. Tempora volu...,Amendoim Erva Doce Groselha Fubá,Et fuga explicabo ex voluptatibus error.,TAG29 TAG93 TAG64 TAG37 TAG25

#### Remove Special Characters

In [53]:
df_recipes['tags'].head()

0      TAG43 TAG49 TAG47 TAG7 TAG91
6       TAG3 TAG7 TAG96 TAG58 TAG68
12    TAG27 TAG42 TAG13 TAG58 TAG83
18      TAG31 TAG73 TAG1 TAG67 TAG5
24      TAG94 TAG91 TAG19 TAG4 TAG8
Name: tags, dtype: object

In [54]:
df_recipes = remove_special_characters(df_recipes, 'tags', special_characters)

C:\Users\rafae\AppData\Local\Temp\ipykernel_23028\3230679304.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[column_name] = df[column_name].str.replace(f'[{re.escape(characters_to_remove)}]', ' ', regex=True)

In [55]:
df_recipes['tags'].head()

0      TAG43 TAG49 TAG47 TAG7 TAG91
6       TAG3 TAG7 TAG96 TAG58 TAG68
12    TAG27 TAG42 TAG13 TAG58 TAG83
18      TAG31 TAG73 TAG1 TAG67 TAG5
24      TAG94 TAG91 TAG19 TAG4 TAG8
Name: tags, dtype: object

### Export dataset

In [56]:
df_recipes.to_csv('dataset/recipes.csv', index=False)